server:
  port: 8001
spring:
  security:
    basic:
      enabled: true
    user:
      name: user
      password: password123
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password123@${eureka.instance.hostname}:${server.port}/eureka/